# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Victor F. Lopes # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/vflopes" target="_blank" rel="noopener">@github</a>.
description_i18n:
  en: >-
    He writes in English about web technology and his experience as a learning journal. Meet him at <a href="https://github.com/vflopes" target="_blank" rel="noopener">@github</a>.
  pt: >-
    Ele escreve em portugues sobre tecnologia web e sua experiencia como um diario de aprendizado. Conheca no <a href="https://github.com/vflopes" target="_blank" rel="noopener">@github</a>.
lang: en # default lang
languages: [en, pt]
default_lang: en
timezone: America/Sao_Paulo # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/vflopes/vflopes.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Jekyll Klisé # author name
  bio: >- # tell to the world
    The minimalist Jekyll theme, light and dark mode support, for running a personal site and blog, 
    meet Klisé theme at <a href="https://github.com/piharpi/jekyll-klise" target="_blank" rel="noopener">@github</a>.
  bio_i18n:
    en: >-
      The minimalist Jekyll theme, with light and dark mode support for running a personal site and blog. Meet Klise theme at <a href="https://github.com/piharpi/jekyll-klise" target="_blank" rel="noopener">@github</a>.
    pt: >-
      O tema Jekyll minimalista, com suporte a modo claro e escuro para manter um site e blog pessoal. Conheca o tema Klise no <a href="https://github.com/piharpi/jekyll-klise" target="_blank" rel="noopener">@github</a>.
  username: username # general username
  github: github_username # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: your-email@email.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      lang: en

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    lang: en
    translation_key:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - jekyll-klise/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
